"""accounts

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-24 04:54:45.993915
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "0002"
down_revision: str | None = "0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "accounts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("phone", sa.String(length=20), nullable=True),
        sa.Column("password_hash", sa.Text(), nullable=True),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("telegram_user_id", sa.BigInteger(), nullable=True),
        sa.Column("is_platform_admin", sa.Boolean(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("lang", sa.String(length=5), nullable=False),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("phone"),
        sa.UniqueConstraint("telegram_user_id"),
    )
    op.add_column("shop_users", sa.Column("account_id", sa.Integer(), nullable=True))
    op.alter_column("shop_users", "telegram_user_id", existing_type=sa.BIGINT(), nullable=True)
    op.create_index(op.f("ix_shop_users_account_id"), "shop_users", ["account_id"], unique=False)
    op.create_unique_constraint("uq_shop_users_shop_account", "shop_users", ["shop_id", "account_id"])
    op.create_foreign_key(
        "fk_shop_users_account", "shop_users", "accounts", ["account_id"], ["id"], ondelete="SET NULL"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_shop_users_account", "shop_users", type_="foreignkey")
    op.drop_constraint("uq_shop_users_shop_account", "shop_users", type_="unique")
    op.drop_index(op.f("ix_shop_users_account_id"), table_name="shop_users")
    # Telegram ulanmagan (faqat web) xodimlarni eski sxemada saqlab bo'lmaydi
    op.execute("DELETE FROM shop_users WHERE telegram_user_id IS NULL")
    op.alter_column("shop_users", "telegram_user_id", existing_type=sa.BIGINT(), nullable=False)
    op.drop_column("shop_users", "account_id")
    op.drop_table("accounts")
    # ### end Alembic commands ###
