"""channel token expiry and display name

Revision ID: 0003
Revises: 0002
Create Date: 2026-09-24 05:56:51.547898
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "0003"
down_revision: str | None = "0002"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("channels", sa.Column("token_expires_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column("channels", sa.Column("display_name", sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("channels", "display_name")
    op.drop_column("channels", "token_expires_at")
    # ### end Alembic commands ###
