"""shop voice settings

Revision ID: 0004
Revises: 0003
Create Date: 2026-09-24 09:54:40.979239
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "0004"
down_revision: str | None = "0003"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("shop_settings", sa.Column("voice_mode", sa.String(length=20), server_default="off", nullable=False))
    op.add_column(
        "shop_settings", sa.Column("voice_gender", sa.String(length=10), server_default="female", nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("shop_settings", "voice_gender")
    op.drop_column("shop_settings", "voice_mode")
    # ### end Alembic commands ###
