"""online payments

Revision ID: 0005
Revises: 0004
Create Date: 2026-09-24 12:16:43.629271
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "0005"
down_revision: str | None = "0004"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("payments", sa.Column("plan", sa.String(length=20), nullable=True))
    op.add_column("payments", sa.Column("months", sa.Integer(), server_default="1", nullable=False))
    op.add_column("payments", sa.Column("state", sa.Integer(), server_default="0", nullable=False))
    op.add_column("payments", sa.Column("provider_create_time", sa.BigInteger(), nullable=True))
    op.add_column("payments", sa.Column("perform_time", sa.DateTime(timezone=True), nullable=True))
    op.add_column("payments", sa.Column("cancel_time", sa.DateTime(timezone=True), nullable=True))
    op.add_column("payments", sa.Column("cancel_reason", sa.Integer(), nullable=True))
    op.create_index(op.f("ix_payments_provider_txn_id"), "payments", ["provider_txn_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_payments_provider_txn_id"), table_name="payments")
    op.drop_column("payments", "cancel_reason")
    op.drop_column("payments", "cancel_time")
    op.drop_column("payments", "perform_time")
    op.drop_column("payments", "provider_create_time")
    op.drop_column("payments", "state")
    op.drop_column("payments", "months")
    op.drop_column("payments", "plan")
    # ### end Alembic commands ###
