"""abandoned cart reminder

Revision ID: 0006
Revises: 0005
Create Date: 2026-09-24 12:31:10.449947
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "0006"
down_revision: str | None = "0005"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("conversations", sa.Column("cart_reminded_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column(
        "shop_settings", sa.Column("cart_reminder_enabled", sa.Boolean(), server_default="true", nullable=False)
    )
    op.add_column("shop_settings", sa.Column("cart_reminder_hours", sa.Integer(), server_default="3", nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("shop_settings", "cart_reminder_hours")
    op.drop_column("shop_settings", "cart_reminder_enabled")
    op.drop_column("conversations", "cart_reminded_at")
    # ### end Alembic commands ###
